image: erlang:19.3

before_script:
  - apt-get update -y
  - apt-get -y install g++-4.9
  - export CXX=g++-4.9

test:
  artifacts:
    when: always
    paths:
    - _build/test/logs
    - _build/test/cover

  script:
    - make test cover